project_name: tlcpchan

before:
  hooks:
    - go mod tidy -C ../tlcpchan
    - go mod tidy -C ../tlcpchan-cli
    - cd ../tlcpchan-ui && npm ci && npm run build

builds:
  - id: tlcpchan
    main: ../tlcpchan
    binary: tlcpchan
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - loong64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: loong64
      - goos: darwin
        goarch: loong64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

  - id: tlcpchan-cli
    main: ../tlcpchan-cli
    binary: tlcpchan-cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - loong64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: loong64
      - goos: darwin
        goarch: loong64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - ../tlcpchan-ui/ui/**/*
      - ../trustedcerts/**/*
      - ../README.md
      - ../LICENSE

nfpms:
  - package_name: tlcpchan
    id: nfpm
    file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    vendor: TLCP Channel
    homepage: https://github.com/Trisia/tlcpchan
    maintainer: TLCP Channel Team
    description: TLCP/TLS 协议代理工具，支持双协议并行工作
    license: Apache-2.0
    formats:
      - deb
      - rpm
    contents:
      - src: tlcpchan
        dst: /etc/tlcpchan/tlcpchan
        file_info:
          mode: 0755
      - src: tlcpchan-cli
        dst: /etc/tlcpchan/tlcpchan-cli
        file_info:
          mode: 0755
      - src: ../tlcpchan-ui/ui
        dst: /etc/tlcpchan/ui
        type: tree
      - src: ../trustedcerts
        dst: /etc/tlcpchan/rootcerts
        type: tree
      - src: ./systemd/tlcpchan.service
        dst: /usr/lib/systemd/system/tlcpchan.service
        file_info:
          mode: 0644
      - dst: /etc/tlcpchan/keystores
        type: dir
        file_info:
          mode: 0755
      - dst: /etc/tlcpchan/logs
        type: dir
        file_info:
          mode: 0755
    scripts:
      postinstall: ./scripts/postinstall.sh
      preremove: ./scripts/preremove.sh
    overrides:
      deb:
        dependencies:
          - ca-certificates
      rpm:
        dependencies:
          - ca-certificates

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
